---
title: "Historical changes in forest densification and migration at the alpine-treeline ecotone in central BC"
author: "Hardy Griesbauer"
date: "12/05/2020"

bibliography: C:\\Users\\hgriesba\\Documents\\Git\\markdownDocs\\Treeline.bib

output:
  word_document:
    reference_docx: C:\\Users\\hgriesba\\Documents\\Git\\markdownDocs\\wordTemplate2.docx
  html_document:
    df_print: paged
csl: C:\\Users\\hgriesba\\Documents\\Git\\markdownDocs\\cjfr.csl

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(captioner)

```

# Introduction

#### introduce the alpine-ecotone as a climatically sensitive ecosystem that may be vulnerable to climate change.
This ecosystem is associated with a range of socioeconomic values including recreation, tourism.
Ecologically, alpine-treeline ecotones are also found in environments that provide important habitat for species at risk such as whitebark pine, mountain ecotypes of woodland Caribou, and grizzly bears.  
Snowmelt from these sites provides important water downhill.
Thus, we need a greater understanding of potential impacts from climate change in these environments.

#### Introduce the alpine-treeline ecotone
At upper elevations, forests change to non-treed ecosystems, such as alpine tundra.  
How is this transition defined?
The boundary between forest and alpine ecosystems can be 'fuzzy' and difficult to discern [@Harsch2011a; @Feuillet2019a].  
A number of tree-based thresholds have been proposed including mean tree heights of and 
In British Columbia, a percentage cover by trees of 10% has been proposed [@MacKenzie2012].
The alpine-treeline boundary can also take a number of forms [@Harsch2011a].  
Diffuse treelines are characterized by a relative gradual decrease in tree height and density, primarily found in environments where summer climate limits growth but not regeneration.   

#### How does climate limit the position of the treeline?
Summer temperatures were once thought to limit the global alpine treeline
treeline position can be controlled through climatic effects on growth and regeneration.  Where cold temperatures or a short growing season prevent sufficient growth, trees may not accumulate sufficient carbon to achieve heights or sexual maturity.  Where this is the primary climatic limitation on growth, the treeline tends to appear diffuse, characterized by a relative gradual decrease in tree height and density [@Harsch2011a]
In other environments, Winter conditions can repeatedly damage trees through severe winds, snow and ice damage, thus limiting the survival of trees.  IN these environments, trees at the treeline may take on a multi-stemmed, prostate form, known as krummholz treeline [@Harsch2011a].  
There are non-climatic controls on the treeline position as well. Abrupt and island treelines may form in areas where treeline expansion is limited by permanent topographical features such as rock outcrops and thin soils, or by localized areas characterized by deep accumulations of snow that persist into the summer and preclude germination.  As well, successful seed germination and survival may be hindered by herbivory and competition from shrubs [@].  In other cases, dense shrub layers can prevent seedfall from reaching the ground [@]

#### Implications of climate on change alpine-treeline ecotone
An increase in tree establishment at the alpine-treeline ecotone can result in a range of phenomena that include; forest densification, increased growth, upward migration of the treeline [@Feuillet2019a], changes to forest species composition; and changes in tree morphology [@Camarera2017b].
About half of the world's treelines have migrated upwards in elevation, presumably associated with warmer temperatures [@Harsch2009]  


Treelines are relatively static and will lag behind climate change for a period of time. As well, the pathway of treeline migration will likely not be linear; rather trees may not rise until a climatic threshold has been exceeded that now allows for tree recruitment.  This will also vary depending on the climatic limitation.  Diffuse treelines may respond relatively quickly in response to warmer summer temperatures, wherewas krummholz treelines might not move until extreme and anomalous conditions lessen.  One severe winter storm can remove growth and form gains from previous decades.


Growth on the other hand, tends to respond at annual and finer temporal scales; therefore, the impacts of climate change in treeline forest may be observed initially in growth responses.
Treeline forests in Europe may reach size and reproductive potential similar to forests in subalpine forests by the middle of the 21st century, with treeline densification accelerating after that [@Camarero2017b].


#### Context for this study
The objectives of this study are to examine diffuse and krummholz treelines in three mountain ranges of central British Columbia, in order to determine historical chnages in treeline position and densification.  We studied this phenomenon at decadal scales through air-photo image analysis, as well as at inter-annual scales through dendrochronological data and satellite imagery.  Our main hypotheses were:
1. In central BC, trees in diffuse treelines are increasing raidal growth in response to warmer trends in the region; 
2. Forests near treeline increased in density over the past century;
3. Treelines are moving up in elevation

Island treeline forms are common in the Omineca and elsewhere in North America [c.f. @Harsch2011a].  Island tan reeline forms may represent two phenomena: (i) the gradual colonization of trees into the alpine tundra starting with the successful establishment of a seedling in the lee of a shletering rock or outcrop, and modifying its local environment in such a way that allowasdasdfdzfor additional seedling establishment; and (ii) a transient establishment of trees that representan
an 
Upward migration and tree densification





# Methods

## Modeling the climatic treeline
To model historical, current and future climatic treelines, we implemented the following process:

1. Create isotherm of FFP 90 days and growing season temperature of 6.7Degree C [@Barredoo2020; @Korner2004;]
2. Compare to VRI data (potentially can use a tree height of 3m to define treeline)
3. Use statistical approach as per Barredo et al. [-@Barredo2020].

Also, pursued our own approach to use VRI data to define treeline position, and then machine learning with ClimateBC variables to predict climatic thresholds defining the treeline position.
1. Define treeline using VRI
2. Apply maybe a 1km buffer around the treeline line
3. 


## Field methods

Within the context of alpine treeline studies, it is important to define what constitutes the treeline and where trees transition from upright organisms to prostate life form more shrub-like in appearance.  

For the purposes of this study, we considered any occurrence of a Picea or Abies species to be a tree, regardless of height or form.  This allowed us to sample individuals that may have only recently become established, but in cases where we sampled trees that were short enough to be covered by snowpack during the winter, these trees may not be necessarily exposed to limiting climate conditions [@Paulsen2000].  Thus, considering seedlings as the upper limit of the treeline might not be accurate, as seedlings can be come successfully established under shelter from small features such as other shrubs and rocks, but can become persistently stuck in shrub form once exposed to the open atmosphere several metres above the ground [@Korner2012].



### Site selection
We targeted areas with diffuse treelines, as these are considered to be most responsive to climate change [@Holt].  We avoided areas with evidence of human, fire or insect disturbance, and avoided areas where obvious soil or topographic features (e.g., cliffs) imposed a non-climatic constraint on the treeline position.

We considered the following approaches to sampling trees at the treeline:

An assessment of treelines in the Omineca indicated that many treelines are an island form, with disjunct islands.  

1. From [@Brown]: At each site we identified the current position of the timberline, defined as the elevation zone where canopy cover was reduced to < 30%.  Canopy cover was measured using a convex densitometer.  We then established three vertical transects, with 10-m diameter circular plots located at 5, 25, 50 and 100 m above and below the current timberline.  Vertical transects were spaced at 25 m intervals across the slope.   Within each plot we took a full census of seedlings, saplings, mature trees, and standing dead stems. Seedlings, saplings and mature trees were defined as upright stems  < 130 cm in height, > 130 cm in height with a diameter at breast height (dbh) < 10 cm, and > 130 cm in height with a dbh  > 10 cm, respectively.  In each plot we randomly selected up to 3 seedlings, 3 saplings and 10 mature trees and sampled them to 
represent the age structure of the population.  Seedlings were uprooted and cross-sectional discs were cut from the base of the stem at the root-shoot boundary.  Increment cores were extracted as close to the base of trees as possible for most saplings and mature trees.  Krummholz were sampled by uprooting the identifiable parent stem and removing a disc sample from the root shoot boundary.  When possible, krummholz were selectively sampled by acquiring disc samples from individuals with single erect stems.

2. 

# Discussion

## Implications of changes in high-altitude forests
- Loss of alpine tundra domain as trees encroach upwards, which will affect hydrology and snow dynamics [@Barredo2020], resulting in downstream impacts on rivers, ecosystems.
- Alpine tundra domain is an island ecosystem, and will shrink over time as forests encroach [@Barredo2020]
- Implications to unique forests such as the inland temperate rainforests of central BC, with strong links between productivity and snowmelt [@reference].
- Uncertain implications for plant assemblages and biodiversity.  Certain specialized alpine plants may lose habitat [@reference].
- 

# References
